language: android

git:
    submodules: true

android:
  components:
  - tools
  - platform-tools
  - tools # tools twice on purpose
  - build-tools-28.0.3
  - android-28

before_install:
   # - echo yes | sdkmanager --licenses && yes | sdkmanager --update
   - echo y | sdkmanager "ndk-bundle"
   - echo y | sdkmanager "cmake;3.10.2.4988404"

install:
# NDK configuration
    - printenv
    - echo `pwd`
    - wget http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin
    - chmod a+x android-ndk-r10d-linux-x86_64.bin
    - ./android-ndk-r10d-linux-x86_64.bin -y | grep -v Extracting # because log will be too long!
    - export NDK_ROOT=`pwd`/android-ndk-r10d
    - echo $NDK_ROOT
    - export PATH=$PATH:$NDK_ROOT
    - echo $PATH

# Android SDK configuration
    - export NDK_ROOT=/usr/local/android-sdk/ndk-bundle
    - export PATH=$PATH:$NDK_ROOT
    - export ANDROID_SDK_ROOT=/usr/local/android-sdk
    - export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools

# cocos setup 
    - cd cocos2d
    - python download-deps.py --remove-download=yes
    - python ./setup.py
    - export COCOS_CONSOLE_ROOT=`pwd`/tools/cocos2d-console/bin
    - export PATH=$PATH:$COCOS_CONSOLE_ROOT
    - export COCOS_TEMPLATES_ROOT=`pwd`/templates
    - export PATH=$PATH:$COCOS_TEMPLATES_ROOT
    - export ANT_ROOT=/usr/share/ant/bin
    - export PATH=$PATH:$ANT_ROOT
    - printenv
    - cd ..

# create project files
    - python build.py -n examples/little-ninja/

script:
    - cocos compile -p android -j 8 --agreement n

after_success:
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_PULL_REQUEST
    - echo $TRAVIS_COMMIT_MESSAGE
    - LATEST_COMMIT_LOG=`git log -1 --oneline`
 