language: android
git:
  submodules: true
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
before_install:
- openssl aes-256-cbc -K $encrypted_e0e99809c00b_key -iv $encrypted_e0e99809c00b_iv
  -in fz.keystore.enc -out fz.keystore -d
- echo y | sdkmanager "ndk-bundle"
- echo y | sdkmanager "cmake;3.10.2.4988404"
install:
- printenv
- echo `pwd`
- echo $NDK_ROOT
- export PATH=$PATH:$NDK_ROOT
- echo $PATH
- export NDK_ROOT=/usr/local/android-sdk/ndk-bundle
- export PATH=$PATH:$NDK_ROOT
- export ANDROID_SDK_ROOT=/usr/local/android-sdk
- export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools
- cd cocos2d
- python download-deps.py --remove-download=yes
- python ./setup.py
- export COCOS_CONSOLE_ROOT=`pwd`/tools/cocos2d-console/bin
- export PATH=$PATH:$COCOS_CONSOLE_ROOT
- export COCOS_TEMPLATES_ROOT=`pwd`/templates
- export PATH=$PATH:$COCOS_TEMPLATES_ROOT
- export ANT_ROOT=/usr/share/ant/bin
- export PATH=$PATH:$ANT_ROOT
- printenv
- cd ..
- python .travis/tag.py
- python build.py -n $SUBMODULE_PATH
script:
- travis_wait 30 cocos compile -p android -m release -j 8 --agreement n
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: nJzuzyz8hsx536AuzCaoa+OrYhsD28CUs6SV8ak1Um/6YyqngARCutmbQCPCEUC8+pjhICtKGgVy1n3znICtWMxNFGkFCR/sU5xZkDj1UV4UTqHgwVNi8WGNSCmLt/5ZIKXrmJSUXM9EXHYrvC5yaoxSIMiYWF1pYA114vrU8Jly7yQgMFiaXLXWniM/0GamWS/iTemJpS15kR5fD8b1WUCOHDRx4yomoqnWh3wiV+H18lfrFJiUs6mu/BdskPuSK5YBkLMBNdpMPWJRVvsz9a85olCp07MaTOdNog9KNWc/3vvrBDNxYVzPpKeIYmOU4bmZsLoSehjWqF+eptvsDwfZOJhGD8QV6Z7PnwgP2NAv/vxEOLNTSO3CHHuD/8wTD0Cj3JvfiNK4tQTkNW7nKo/q8R3bk+QSWXPJHrW4IZ1O+MmRk7JC1dGZN7/Vt0XHE1QRvPucm3DXp4VQptYQE06pOaW7iSrwxn22vuASWfx/7rphsJjcO/dTvLbMHgQnKMYEd6lKXKuBWT//HQNIn1Re46OOyVJFAaK4df9MV4OB64voF7+NKBe+fQfX5/8ckspHzqHNGGRPgCRx7uXdY/ybvsiENf4i0x93euWt1NUlwkH4UHYHdINgmbG4ZEDrpcyw5PLti0CfOc14axN5nse+DlNS6L8Lo+6Y5oWUicM=
  file_glob: true
  file: bin/release/android/*
  on:
    tags: true
env:
  global:
  - secure: GyZ4pIpjHErVb4zASS2/+Xxqzc39mfNT9Zdk9cMGEYQAO1s9BYUmyvNdtQeiVR5gpj7m9gnPUgCw6cFZ83pTfqWeCcXiCddAxnYiGIzP6eclPONpKdT84q44FMrgA8l/+yOYjwwTSpUP5fUroOHVk7krLcjMB8MWStHlAAPX26gY11ZW6dLFbLXKxGQJvRaU1YGDrgPmbRzwUg0OeEFxx6wPDrEF8puZ5T+ez6J90F/YgdGnuDtV/DAXSjdAIyuFsxJvKyI6zeBKZ96/r5a+b97vl/qXQ9JUhZFaRWFSEIUUPDfYzTWeIhBdQCI3hictfFhJCiRlSd6QVhrjywws94pdFOv+5XrE26rL34sC1yQ/oxudO8s9+onnAYAo6vYVrhYsznHiM4HpU2wkk8b52Tchz5J4nRxBN+AZTXh8WjITEsGcpaCgN0hTG4Y9O2wTok7QFfr8THzEnYz1fYD/Q8on+O66HLF0KqUtqpvFpoyVgLquwtQG0PVc5Ri48vUF8xfJx7YQDsMmw8LS3MnWKGI9+JN5E3JHdGCuPGxOzKLeBnzl0SUHUZH597nocaHKC33Wtd+t8ubkiEBoSfg/kjycoywQ7IUvmsWLNBHZ2lVNJy5i+Dtlio9/hs+araFweiNfO8bVmdraTAxRO7EljjGwrc0j9dPgOUUzXVK/SwA=
  - secure: diRCr9NX2wz9NQm8YpSElvqG3Z7zM4Jv01gCFvm/jo2u17lPwWm0P+Yd5Yp7JjB5b6KzUUF9MaVbD30AAN/BM4ZihAtv4Vmcu5eBZjXkbmy1T7QIbQFdF4X2GizgaOIBtt5oq/qLMehNVY/2dPWuOu1laaOdFwMMxMnGbOT4ZLnc/+GMw2BhVAP2M+pIDtKD/nPB4pU4dVU+6H/C7LXL717fX7z26nQBD6i+zvx4B/l10Nl9j/j4tjgYLEDGqGH8lNj313Ti6g6BjYUtbWjuDOREE4g5k5V+BfWrWkflKVy71gxb4tL0fSDdMRAu3sXDcxSK4G86X7Z673iTd9jQDqaDU8ug4BdmI4U4Wa/PeRjgF5YTKh0CFsrYgH/DIcN5ma95Ur6pg+Pk6oaieAPLZRcdjmoCVoNM+FuOGrUdHygAQQ7SyI26jR6A1bEW9VeOd0488KESoRkE+5/ckKdmWnRB9+EdstdWYwKHAt39tsN5LLURdgsOkxQqhbKNILDdMvlVyoq5uRJlSYeI3ALukQU11RsQLq3wqGouChoss5JLHAVibsAuWnyN5R4TZYIWiTcUgJOEyfpf86l+Gk6skrMH8C+xFN0b2B/DtxHqUya7Ka8ANSD/a8BwJyZPXG8FTF2Q64qd3u56FGJHviACW8UTH0uGTizejymsazH7eig=
  - secure: EiIkieFohSX3tyIRbzb337ddgaeYp55eqZh2S6OghxEvYSGNMbFNeDCi16mYLN0LGaqoNhwf4FH1rzwoR9MQ0IgjbzFMpmADRE0CVyIvhTZCXr1GZKN9dgsyThppGbx0dpKv6XhFbA/LWSoF2IUp7QgYxaA+3oxZqq11aVQMH9Uo8C8W0hb6dchB7u/x7UN0ZVdtqzfXxIo+/HnWzhHPp8V+XNWrJgHSlqqeF/sdy6Tk1bDVObVImwvYDj7R33KbVFFOewGWMGyXiWDfGJwbjomVpyIwoDc7qnWE1Y8m7tG43SPX4yeQZkb8v5C+0NUSzUDYJA10lv7vfKw8Ynj89Sk04kJafVL4oa1zfxYAbk1wEfsSuC44VPdl/+G7817nqrPzttrWvzXqxhHRbvdoUQPT1lDtgLvBwopHjzHOUweDSo9dvCZux64TFFOQ0m4O3KMonQEWNe0KtLLkIb4bGkm1aVw2b8eE+ECwRg4/gdQTbKxD3Rt0lYpbjtE+4S2M1WBo3OR2+MhiNbGY9/h+3EayIUrcJqXkSqZ7kTCfMHDX13fMBTMYp4WVsNXqGkWSgI29FANSk9S3ipYMoU8gWOEguWirXydm7mH/asyiFBwDGAGF3ig9iLf3kVfvauQa72H2Tz8FYMSKSm5edP0sKXZx2lE5cuw6E9JupdrZFZ8=
